const LS_KEY = 'oikos-card-cfg-vacuum'

export const VACUUM_DEFAULTS = {
  name: 'Dreame Vacuum',
  vacuumEntity:          'vacuum.ambrogio_2',
  cameraEntity:          'camera.ambrogio_map',
  batteryEntity:         'sensor.ambrogio_battery_level',
  stateEntity:           'sensor.ambrogio_state',
  statusEntity:          'sensor.ambrogio_status',
  chargingEntity:        'sensor.ambrogio_charging_status',
  currentRoomEntity:     'sensor.ambrogio_current_room',
  errorEntity:           'sensor.ambrogio_error',
  cleaningTimeEntity:    'sensor.ambrogio_cleaning_time',
  cleanedAreaEntity:     'sensor.ambrogio_cleaned_area',
  cleaningProgressEntity:'sensor.ambrogio_cleaning_progress',
  mainBrushEntity:       'sensor.ambrogio_main_brush_left',
  mainBrushDaysEntity:   'sensor.ambrogio_main_brush_time_left',
  sideBrushEntity:       'sensor.ambrogio_side_brush_left',
  sideBrushDaysEntity:   'sensor.ambrogio_side_brush_time_left',
  filterEntity:          'sensor.ambrogio_filter_left',
  filterDaysEntity:      'sensor.ambrogio_filter_time_left',
  sensorDirtyEntity:     'sensor.ambrogio_sensor_dirty_left',
  sensorDirtyDaysEntity: 'sensor.ambrogio_sensor_dirty_time_left',
  suctionLevelEntity:    'select.ambrogio_suction_level',
  cleaningModeEntity:    'select.ambrogio_cleaning_mode',
  waterTempEntity:       'select.ambrogio_water_temperature',
  dryingTimeEntity:      'select.ambrogio_drying_time',
  mopFreqEntity:         'select.ambrogio_mop_extend_frequency',
  cleaningRouteEntity:   'select.ambrogio_cleaning_route',
  autoEmptyEntity:       'sensor.ambrogio_auto_empty_status',
  selfWashEntity:        'sensor.ambrogio_self_wash_base_status',
  dustBagEntity:         'sensor.ambrogio_dust_bag_status',
  mopPadEntity:          'sensor.ambrogio_mop_pad',
  detergentEntity:       'sensor.ambrogio_detergent_status',
  dirtyWaterEntity:      'sensor.ambrogio_dirty_water_tank_status',
  hotWaterEntity:        'sensor.ambrogio_hot_water_status',
  lowWaterEntity:        'sensor.ambrogio_low_water_warning',
  dustCollectionEntity:  'sensor.ambrogio_dust_collection',
  drainageEntity:        'sensor.ambrogio_drainage_status',
  autoEmptyModeEntity:   'select.ambrogio_auto_empty_mode',
  smartMopWashingEntity: 'switch.ambrogio_smart_mop_washing',
  washingModeEntity:     'select.ambrogio_washing_mode',
  mopWashLevelEntity:    'select.ambrogio_mop_wash_level',
  autoRewashingEntity:   'select.ambrogio_auto_rewashing',
  selfCleanFreqEntity:   'select.ambrogio_self_clean_frequency',
  selfCleanAreaEntity:   'number.ambrogio_self_clean_area',
  selfCleanTimeEntity:   'number.ambrogio_self_clean_time',
  startAutoEmptyEntity:  'button.ambrogio_start_auto_empty',
  startSelfWashEntity:   'button.ambrogio_self_clean',
  startDryingEntity:     'button.ambrogio_manual_drying',
  autoDetergentEntity:   'switch.ambrogio_auto_water_refilling',
  autoWashEntity:        'switch.ambrogio_auto_mount_mop',
  dndEntity:             'switch.ambrogio_dnd',
  carpetBoostEntity:     'switch.ambrogio_carpet_boost',
  selfCleanSwitchEntity: 'switch.ambrogio_self_clean',
  autoDryingEntity:      'switch.ambrogio_auto_drying',
  obstacleEntity:        'switch.ambrogio_obstacle_avoidance',
  resumeEntity:          'switch.ambrogio_resume_cleaning',
  cleanGeniusEntity:     'select.ambrogio_cleangenius',
  cleanGeniusModeEntity: 'select.ambrogio_cleangenius_mode',
  deepCleanEntity:       'switch.ambrogio_intensive_carpet_cleaning',
  maxSuctionEntity:      'switch.ambrogio_max_suction_power',
  humidityEntity:        'number.ambrogio_wetness_level',
  mopPadLifeEntity:      '',
  mopPadLifeDaysEntity:  '',
  silverIonEntity:       '',
  silverIonDaysEntity:   '',
  totalAreaEntity:       'sensor.ambrogio_total_cleaned_area',
  countEntity:           'sensor.ambrogio_cleaning_count',
  totalTimeEntity:       'sensor.ambrogio_total_cleaning_time',
  firstCleanEntity:      'sensor.ambrogio_first_cleaning_date',
  rooms: [
    { id: 9, name: 'Camera da Letto' },
    { id: 1, name: 'Bagno Grande'    },
    { id: 2, name: 'Cameretta piccola'},
    { id: 3, name: 'Cameretta Grande' },
    { id: 6, name: 'Bagno Piccolo'   },
    { id: 5, name: 'Corridoio'       },
    { id: 7, name: 'Cucina'          },
    { id: 8, name: 'Salone'          },
  ],
}

export function getVacuumConfig() {
  try {
    const raw = localStorage.getItem(LS_KEY)
    if (raw) return { ...VACUUM_DEFAULTS, ...JSON.parse(raw) }
  } catch {}
  return { ...VACUUM_DEFAULTS }
}

export function saveVacuumConfig(cfg) {
  localStorage.setItem(LS_KEY, JSON.stringify(cfg))
}

// Genera tutte le entità dal prefisso dispositivo Tasshack/Dreame
// es. "vacuum.ambrogio_2" → prefix "ambrogio" → "sensor.ambrogio_battery_level" ...
export function derivePrefix(vacuumEntityId) {
  if (!vacuumEntityId || !vacuumEntityId.startsWith('vacuum.')) return null
  return vacuumEntityId.replace(/^vacuum\./, '').replace(/_\d+$/, '')
}

export function buildEntityMap(prefix) {
  const s = (n) => `sensor.${prefix}_${n}`
  const sel = (n) => `select.${prefix}_${n}`
  const sw = (n) => `switch.${prefix}_${n}`
  return {
    cameraEntity:           `camera.${prefix}_map`,
    batteryEntity:          s('battery_level'),
    stateEntity:            s('state'),
    statusEntity:           s('status'),
    chargingEntity:         s('charging_status'),
    currentRoomEntity:      s('current_room'),
    errorEntity:            s('error'),
    cleaningTimeEntity:     s('cleaning_time'),
    cleanedAreaEntity:      s('cleaned_area'),
    cleaningProgressEntity: s('cleaning_progress'),
    mainBrushEntity:        s('main_brush_left'),
    mainBrushDaysEntity:    s('main_brush_time_left'),
    sideBrushEntity:        s('side_brush_left'),
    sideBrushDaysEntity:    s('side_brush_time_left'),
    filterEntity:           s('filter_left'),
    filterDaysEntity:       s('filter_time_left'),
    sensorDirtyEntity:      s('sensor_dirty_left'),
    sensorDirtyDaysEntity:  s('sensor_dirty_time_left'),
    humidityEntity:         `number.${prefix}_wetness_level`,
    mopPadLifeEntity:       '',
    mopPadLifeDaysEntity:   '',
    silverIonEntity:        '',
    silverIonDaysEntity:    '',
    suctionLevelEntity:     sel('suction_level'),
    cleaningModeEntity:     sel('cleaning_mode'),
    waterTempEntity:        sel('water_temperature'),
    dryingTimeEntity:       sel('drying_time'),
    mopFreqEntity:          sel('mop_extend_frequency'),
    cleaningRouteEntity:    sel('cleaning_route'),
    autoEmptyEntity:        s('auto_empty_status'),
    selfWashEntity:         s('self_wash_base_status'),
    dustBagEntity:          s('dust_bag_status'),
    mopPadEntity:           s('mop_pad'),
    detergentEntity:        s('detergent_status'),
    dirtyWaterEntity:       s('dirty_water_tank_status'),
    hotWaterEntity:         s('hot_water_status'),
    lowWaterEntity:         s('low_water_warning'),
    dustCollectionEntity:   s('dust_collection'),
    drainageEntity:         s('drainage_status'),
    autoEmptyModeEntity:    sel('auto_empty_mode'),
    smartMopWashingEntity:  sw('smart_mop_washing'),
    washingModeEntity:      sel('washing_mode'),
    mopWashLevelEntity:     sel('mop_wash_level'),
    autoRewashingEntity:    sel('auto_rewashing'),
    selfCleanFreqEntity:    sel('self_clean_frequency'),
    selfCleanAreaEntity:    `number.${prefix}_self_clean_area`,
    selfCleanTimeEntity:    `number.${prefix}_self_clean_time`,
    startAutoEmptyEntity:   `button.${prefix}_start_auto_empty`,
    startSelfWashEntity:    `button.${prefix}_self_clean`,
    startDryingEntity:      `button.${prefix}_manual_drying`,
    autoDetergentEntity:    sw('auto_water_refilling'),
    autoWashEntity:         sw('auto_mount_mop'),
    dndEntity:              sw('dnd'),
    carpetBoostEntity:      sw('carpet_boost'),
    selfCleanSwitchEntity:  sw('self_clean'),
    autoDryingEntity:       sw('auto_drying'),
    obstacleEntity:         sw('obstacle_avoidance'),
    resumeEntity:           sw('resume_cleaning'),
    cleanGeniusEntity:      sel('cleangenius'),
    cleanGeniusModeEntity:  sel('cleangenius_mode'),
    deepCleanEntity:        sw('intensive_carpet_cleaning'),
    maxSuctionEntity:       sw('max_suction_power'),
    totalAreaEntity:        s('total_cleaned_area'),
    countEntity:            s('cleaning_count'),
    totalTimeEntity:        s('total_cleaning_time'),
    firstCleanEntity:       s('first_cleaning_date'),
  }
}
